stages:
  - deploy

deploy-site:
  stage: deploy
  script:
    - ssh maniak 'cd ~/sites/maki-group.mg/kotikota.maki-group.mg/wp-content/themes/kotikota && git checkout -- . && git pull origin master'
  tags:
    - devmaki
  only:
    - master
